// ============================================
// Bill Library — Preset bills across categories
// Democracy 4-style bill proposals
// ============================================

import { BillTemplate } from './types';

export const BILL_LIBRARY: BillTemplate[] = [
  // ===== ECONOMY (10 bills) =====
  {
    id: 'bill_ubi',
    name: 'Universal Basic Income',
    description: 'Provide every citizen a guaranteed monthly income regardless of employment status.',
    category: 'economy',
    policyChanges: [
      { policyId: 'unemployment_benefits', targetValue: 90 },
      { policyId: 'govt_spending', targetValue: 80 },
    ],
    cost: 3,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'workers', effect: 15 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'business', effect: -15 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 30, conservative: 10 },
  },
  {
    id: 'bill_wealth_tax',
    name: 'Wealth Tax',
    description: 'Annual tax on net worth above $10 million to fund public services.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'business', effect: -20 },
      { voterGroup: 'liberals', effect: 8 },
      { voterGroup: 'rural', effect: 3 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 35, conservative: 10 },
  },
  {
    id: 'bill_corporate_tax_reform',
    name: 'Corporate Tax Reform',
    description: 'Close loopholes and raise effective corporate tax rate to fund infrastructure.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: -18 },
      { voterGroup: 'environmentalists', effect: 3 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 45, conservative: 15 },
  },
  {
    id: 'bill_minimum_wage_increase',
    name: 'Minimum Wage Increase',
    description: 'Raise the national minimum wage by 40% to a living wage standard.',
    category: 'economy',
    policyChanges: [
      { policyId: 'minimum_wage', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: 18 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'business', effect: -12 },
      { voterGroup: 'rural', effect: 5 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 50, conservative: 20 },
  },
  {
    id: 'bill_flat_tax',
    name: 'Flat Tax Act',
    description: 'Replace progressive income tax with a single flat rate of 20% for all earners.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 30 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 18 },
      { voterGroup: 'workers', effect: -10 },
      { voterGroup: 'retirees', effect: -5 },
      { voterGroup: 'liberals', effect: -8 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 40, conservative: 80 },
  },
  {
    id: 'bill_free_trade',
    name: 'Free Trade Expansion',
    description: 'Eliminate tariffs and open borders to international commerce.',
    category: 'economy',
    policyChanges: [
      { policyId: 'trade_openness', targetValue: 90 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'workers', effect: -8 },
      { voterGroup: 'rural', effect: -10 },
      { voterGroup: 'patriots', effect: -12 },
    ],
    ideologyAlignment: { progressive: 40, centrist: 65, conservative: 50 },
  },
  {
    id: 'bill_tech_investment',
    name: 'National Tech Investment Fund',
    description: 'Create a sovereign tech fund to invest in AI, biotech, and green energy startups.',
    category: 'economy',
    policyChanges: [
      { policyId: 'tech_research', targetValue: 80 },
      { policyId: 'govt_spending', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'rural', effect: -3 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 70, conservative: 40 },
  },
  {
    id: 'bill_austerity',
    name: 'Austerity Measures Act',
    description: 'Slash government spending across the board to reduce national debt.',
    category: 'economy',
    policyChanges: [
      { policyId: 'govt_spending', targetValue: 20 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'business', effect: 12 },
      { voterGroup: 'workers', effect: -15 },
      { voterGroup: 'retirees', effect: -12 },
      { voterGroup: 'youth', effect: -8 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 35, conservative: 75 },
  },
  {
    id: 'bill_bank_regulation',
    name: 'Banking Regulation Act',
    description: 'Impose strict regulations on banks including leverage limits and stress tests.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 50 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: -10 },
      { voterGroup: 'liberals', effect: 6 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_pension_reform',
    name: 'Pension Reform Act',
    description: 'Restructure the pension system: raise retirement age, increase contributions.',
    category: 'economy',
    policyChanges: [
      { policyId: 'pensions', targetValue: 40 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'retirees', effect: -20 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'youth', effect: 5 },
      { voterGroup: 'workers', effect: -5 },
    ],
    ideologyAlignment: { progressive: 15, centrist: 50, conservative: 65 },
  },

  // ===== HEALTHCARE (5 bills) =====
  {
    id: 'bill_universal_healthcare',
    name: 'Universal Healthcare Act',
    description: 'Establish a single-payer national health service covering all citizens.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 95 },
      { policyId: 'govt_spending', targetValue: 70 },
    ],
    cost: 4,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'workers', effect: 20 },
      { voterGroup: 'retirees', effect: 18 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'business', effect: -15 },
      { voterGroup: 'rural', effect: 10 },
    ],
    ideologyAlignment: { progressive: 90, centrist: 50, conservative: 15 },
  },
  {
    id: 'bill_private_healthcare_ban',
    name: 'Private Healthcare Ban',
    description: 'Outlaw private healthcare providers to ensure equal access for all.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 100 },
    ],
    cost: 3,
    constitutionalScore: 35,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'business', effect: -25 },
      { voterGroup: 'liberals', effect: -8 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 15, conservative: 5 },
  },
  {
    id: 'bill_mental_health',
    name: 'Mental Health Funding Act',
    description: 'Massively expand mental health services, counseling, and crisis intervention.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'liberals', effect: 10 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'workers', effect: 5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 65, conservative: 35 },
  },
  {
    id: 'bill_drug_pricing',
    name: 'Drug Price Control Act',
    description: 'Cap pharmaceutical prices and allow government bulk purchasing.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 15 },
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'business', effect: -12 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 55, conservative: 20 },
  },
  {
    id: 'bill_health_privatization',
    name: 'Healthcare Privatization',
    description: 'Transition public health services to private providers for efficiency.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 25 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'workers', effect: -15 },
      { voterGroup: 'retirees', effect: -18 },
      { voterGroup: 'rural', effect: -10 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 30, conservative: 70 },
  },

  // ===== EDUCATION (5 bills) =====
  {
    id: 'bill_free_university',
    name: 'Free University Education',
    description: 'Abolish tuition fees at all public universities funded by tax revenue.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 90 },
      { policyId: 'govt_spending', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'youth', effect: 25 },
      { voterGroup: 'liberals', effect: 12 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'business', effect: -8 },
      { voterGroup: 'retirees', effect: -3 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 45, conservative: 10 },
  },
  {
    id: 'bill_school_vouchers',
    name: 'School Voucher Program',
    description: 'Give parents vouchers to choose any school, including private institutions.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 45 },
    ],
    cost: 2,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'religious', effect: 15 },
      { voterGroup: 'business', effect: 8 },
      { voterGroup: 'liberals', effect: -10 },
      { voterGroup: 'urban', effect: -5 },
    ],
    ideologyAlignment: { progressive: 15, centrist: 45, conservative: 75 },
  },
  {
    id: 'bill_stem_funding',
    name: 'STEM Education Investment',
    description: 'Triple funding for science, technology, engineering, and mathematics programs.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 75 },
      { policyId: 'tech_research', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'urban', effect: 8 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 75, conservative: 50 },
  },
  {
    id: 'bill_teacher_pay',
    name: 'Teacher Pay Increase Act',
    description: 'Raise teacher salaries by 30% to attract top talent to education.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'rural', effect: 6 },
      { voterGroup: 'liberals', effect: 5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 60, conservative: 35 },
  },
  {
    id: 'bill_vocational_training',
    name: 'Vocational Training Expansion',
    description: 'Fund apprenticeships and trade schools as alternatives to university.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'workers', effect: 12 },
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: 6 },
    ],
    ideologyAlignment: { progressive: 50, centrist: 70, conservative: 60 },
  },

  // ===== ENVIRONMENT (5 bills) =====
  {
    id: 'bill_carbon_tax',
    name: 'Carbon Tax Act',
    description: 'Tax carbon emissions at $50/ton, rebating proceeds equally to all citizens.',
    category: 'environment',
    policyChanges: [
      { policyId: 'carbon_tax', targetValue: 80 },
      { policyId: 'env_regulations', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 25 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'business', effect: -18 },
      { voterGroup: 'rural', effect: -12 },
      { voterGroup: 'workers', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_green_new_deal',
    name: 'Green New Deal',
    description: 'Massive investment in renewable energy, green jobs, and emissions reduction.',
    category: 'environment',
    policyChanges: [
      { policyId: 'renewables', targetValue: 95 },
      { policyId: 'env_regulations', targetValue: 85 },
      { policyId: 'govt_spending', targetValue: 75 },
    ],
    cost: 4,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 30 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'business', effect: -20 },
      { voterGroup: 'rural', effect: -10 },
      { voterGroup: 'workers', effect: 5 },
    ],
    ideologyAlignment: { progressive: 90, centrist: 30, conservative: 5 },
  },
  {
    id: 'bill_fracking_ban',
    name: 'Fracking Ban',
    description: 'Permanently ban hydraulic fracturing for oil and gas extraction.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 20 },
      { voterGroup: 'rural', effect: -15 },
      { voterGroup: 'workers', effect: -8 },
      { voterGroup: 'business', effect: -10 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 30, conservative: 10 },
  },
  {
    id: 'bill_wildlife_protection',
    name: 'Wildlife Protection Act',
    description: 'Expand protected areas by 30% and increase penalties for poaching.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 70 },
      { policyId: 'agriculture', targetValue: 40 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 18 },
      { voterGroup: 'rural', effect: -12 },
      { voterGroup: 'liberals', effect: 6 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 55, conservative: 30 },
  },
  {
    id: 'bill_nuclear_energy',
    name: 'Nuclear Energy Expansion',
    description: 'Build 10 new nuclear power plants for clean baseload electricity.',
    category: 'environment',
    policyChanges: [
      { policyId: 'renewables', targetValue: 65 },
      { policyId: 'tech_research', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'environmentalists', effect: -8 },
      { voterGroup: 'rural', effect: -5 },
      { voterGroup: 'youth', effect: 3 },
    ],
    ideologyAlignment: { progressive: 35, centrist: 60, conservative: 55 },
  },

  // ===== SECURITY (5 bills) =====
  {
    id: 'bill_police_reform',
    name: 'Police Reform Act',
    description: 'Mandate body cameras, de-escalation training, and civilian oversight boards.',
    category: 'security',
    policyChanges: [
      { policyId: 'police', targetValue: 55 },
      { policyId: 'civil_rights', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'patriots', effect: -10 },
      { voterGroup: 'religious', effect: -3 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 50, conservative: 15 },
  },
  {
    id: 'bill_surveillance',
    name: 'National Surveillance Act',
    description: 'Expand electronic surveillance powers for intelligence agencies.',
    category: 'security',
    policyChanges: [
      { policyId: 'intelligence', targetValue: 85 },
      { policyId: 'civil_rights', targetValue: 30 },
    ],
    cost: 2,
    constitutionalScore: 30,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 12 },
      { voterGroup: 'liberals', effect: -20 },
      { voterGroup: 'youth', effect: -10 },
      { voterGroup: 'religious', effect: 3 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 35, conservative: 70 },
  },
  {
    id: 'bill_gun_control',
    name: 'Comprehensive Gun Control',
    description: 'Ban assault weapons, require background checks and licensing for all firearms.',
    category: 'security',
    policyChanges: [
      { policyId: 'gun_control', targetValue: 85 },
    ],
    cost: 2,
    constitutionalScore: 45,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'rural', effect: -18 },
      { voterGroup: 'patriots', effect: -15 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 45, conservative: 10 },
  },
  {
    id: 'bill_military_expansion',
    name: 'Military Modernization Act',
    description: 'Double the defense budget to modernize armed forces and expand capabilities.',
    category: 'security',
    policyChanges: [
      { policyId: 'military', targetValue: 85 },
      { policyId: 'govt_spending', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 22 },
      { voterGroup: 'business', effect: 5 },
      { voterGroup: 'environmentalists', effect: -8 },
      { voterGroup: 'liberals', effect: -10 },
      { voterGroup: 'workers', effect: -3 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 40, conservative: 85 },
  },
  {
    id: 'bill_cyber_defense',
    name: 'Cyber Defense Initiative',
    description: 'Create a national cyber defense force to protect critical infrastructure.',
    category: 'security',
    policyChanges: [
      { policyId: 'intelligence', targetValue: 70 },
      { policyId: 'tech_research', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 82,
    popularityEffects: [
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'patriots', effect: 8 },
    ],
    ideologyAlignment: { progressive: 45, centrist: 70, conservative: 65 },
  },

  // ===== SOCIAL (5 bills) =====
  {
    id: 'bill_marriage_equality',
    name: 'Marriage Equality Act',
    description: 'Legalize same-sex marriage nationwide with full equal rights.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 80 },
    ],
    cost: 1,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 20 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'religious', effect: -20 },
      { voterGroup: 'rural', effect: -8 },
    ],
    ideologyAlignment: { progressive: 90, centrist: 55, conservative: 10 },
  },
  {
    id: 'bill_drug_decriminalization',
    name: 'Drug Decriminalization',
    description: 'Decriminalize personal drug use, redirect funding to treatment programs.',
    category: 'social',
    policyChanges: [
      { policyId: 'drug_policy', targetValue: 80 },
      { policyId: 'civil_rights', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'religious', effect: -15 },
      { voterGroup: 'patriots', effect: -12 },
      { voterGroup: 'rural', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 35, conservative: 5 },
  },
  {
    id: 'bill_abortion_rights',
    name: 'Reproductive Rights Act',
    description: 'Enshrine abortion access as a protected right in national law.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 50,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 20 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'religious', effect: -25 },
      { voterGroup: 'rural', effect: -8 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 40, conservative: 5 },
  },
  {
    id: 'bill_press_protection',
    name: 'Press Freedom Protection',
    description: 'Shield journalists from prosecution and mandate government transparency.',
    category: 'social',
    policyChanges: [
      { policyId: 'press_freedom', targetValue: 90 },
    ],
    cost: 1,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'urban', effect: 5 },
      { voterGroup: 'patriots', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 65, conservative: 30 },
  },
  {
    id: 'bill_traditional_values',
    name: 'Traditional Values Act',
    description: 'Promote traditional family structures through tax breaks and education policy.',
    category: 'social',
    policyChanges: [
      { policyId: 'religious_freedom', targetValue: 80 },
      { policyId: 'civil_rights', targetValue: 35 },
    ],
    cost: 2,
    constitutionalScore: 50,
    popularityEffects: [
      { voterGroup: 'religious', effect: 22 },
      { voterGroup: 'rural', effect: 12 },
      { voterGroup: 'retirees', effect: 8 },
      { voterGroup: 'liberals', effect: -18 },
      { voterGroup: 'youth', effect: -15 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 85 },
  },

  // ===== IMMIGRATION (3 bills) =====
  {
    id: 'bill_border_wall',
    name: 'Border Wall Construction',
    description: 'Build a fortified border wall and increase border patrol staffing.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'border_security', targetValue: 90 },
      { policyId: 'immigration', targetValue: 15 },
    ],
    cost: 3,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 25 },
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'liberals', effect: -20 },
      { voterGroup: 'youth', effect: -8 },
      { voterGroup: 'business', effect: -5 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 85 },
  },
  {
    id: 'bill_path_citizenship',
    name: 'Path to Citizenship',
    description: 'Create a legal pathway to citizenship for undocumented residents.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 80 },
      { policyId: 'civil_rights', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'workers', effect: 3 },
      { voterGroup: 'patriots', effect: -20 },
      { voterGroup: 'rural', effect: -10 },
      { voterGroup: 'religious', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_refugee_program',
    name: 'Refugee Resettlement Program',
    description: 'Expand refugee intake by 200% and provide integration support services.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 85 },
      { policyId: 'foreign_aid', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'religious', effect: 5 },
      { voterGroup: 'patriots', effect: -18 },
      { voterGroup: 'rural', effect: -10 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 40, conservative: 10 },
  },
];

export const BILL_CATEGORIES = [
  { id: 'economy', name: 'Economy', icon: '💰' },
  { id: 'healthcare', name: 'Healthcare', icon: '🏥' },
  { id: 'education', name: 'Education', icon: '🎓' },
  { id: 'environment', name: 'Environment', icon: '🌿' },
  { id: 'security', name: 'Security', icon: '🛡️' },
  { id: 'social', name: 'Social', icon: '⚖️' },
  { id: 'immigration', name: 'Immigration', icon: '🌍' },
] as const;

export function getBillTemplate(id: string): BillTemplate | undefined {
  return BILL_LIBRARY.find(b => b.id === id);
}

export function getBillsByCategory(category: string): BillTemplate[] {
  return BILL_LIBRARY.filter(b => b.category === category);
}
