// ============================================
// Bill Library — 120+ bills across 7 categories
// Democracy 4-style bill proposals
// ============================================

import { BillTemplate } from './types';

export const BILL_LIBRARY: BillTemplate[] = [
  // ===== ECONOMY (30 bills) =====
  {
    id: 'bill_ubi',
    name: 'Universal Basic Income',
    description: 'Provide every citizen a guaranteed monthly income regardless of employment status.',
    category: 'economy',
    policyChanges: [
      { policyId: 'unemployment_benefits', targetValue: 90 },
      { policyId: 'govt_spending', targetValue: 80 },
    ],
    cost: 3,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'workers', effect: 15 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'business', effect: -15 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 30, conservative: 10 },
  },
  {
    id: 'bill_ubi_basic',
    name: 'Basic Income Pilot',
    description: 'Small-scale basic income trial in select regions — $500/month for qualifying households.',
    category: 'economy',
    policyChanges: [
      { policyId: 'unemployment_benefits', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'business', effect: -5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 45, conservative: 15 },
  },
  {
    id: 'bill_wealth_tax',
    name: 'Progressive Wealth Tax',
    description: 'Annual tax on net worth above $10 million to fund public services.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'business', effect: -20 },
      { voterGroup: 'liberals', effect: 8 },
      { voterGroup: 'rural', effect: 3 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 35, conservative: 10 },
  },
  {
    id: 'bill_flat_wealth_tax',
    name: 'Flat Wealth Tax',
    description: 'A flat 1% annual tax on all assets above $1 million — simpler than progressive brackets.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'business', effect: -12 },
      { voterGroup: 'retirees', effect: -3 },
    ],
    ideologyAlignment: { progressive: 55, centrist: 50, conservative: 25 },
  },
  {
    id: 'bill_corporate_tax_reform',
    name: 'Corporate Tax Reform',
    description: 'Close loopholes and raise effective corporate tax rate to fund infrastructure.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: -18 },
      { voterGroup: 'environmentalists', effect: 3 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 45, conservative: 15 },
  },
  {
    id: 'bill_corporate_tax_cut',
    name: 'Corporate Tax Cut',
    description: 'Slash corporate tax rate to 15% to attract foreign investment and boost hiring.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 20 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'business', effect: 22 },
      { voterGroup: 'workers', effect: -10 },
      { voterGroup: 'liberals', effect: -8 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 35, conservative: 80 },
  },
  {
    id: 'bill_corporate_tax_increase',
    name: 'Corporate Tax Increase',
    description: 'Raise corporate tax to 35% to fund social programs and reduce inequality.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'workers', effect: 12 },
      { voterGroup: 'business', effect: -22 },
      { voterGroup: 'liberals', effect: 6 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 30, conservative: 5 },
  },
  {
    id: 'bill_minimum_wage_increase',
    name: 'National Minimum Wage Increase',
    description: 'Raise the national minimum wage by 40% to a living wage standard.',
    category: 'economy',
    policyChanges: [
      { policyId: 'minimum_wage', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: 18 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'business', effect: -12 },
      { voterGroup: 'rural', effect: 5 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 50, conservative: 20 },
  },
  {
    id: 'bill_minimum_wage_local',
    name: 'Local Minimum Wage Flexibility',
    description: 'Allow regions to set their own minimum wage based on local cost of living.',
    category: 'economy',
    policyChanges: [
      { policyId: 'minimum_wage', targetValue: 55 },
    ],
    cost: 1,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'rural', effect: 8 },
      { voterGroup: 'business', effect: 5 },
      { voterGroup: 'workers', effect: -3 },
      { voterGroup: 'urban', effect: -5 },
    ],
    ideologyAlignment: { progressive: 30, centrist: 60, conservative: 55 },
  },
  {
    id: 'bill_minimum_wage_indexed',
    name: 'Inflation-Indexed Minimum Wage',
    description: 'Tie minimum wage to inflation so it automatically adjusts each year.',
    category: 'economy',
    policyChanges: [
      { policyId: 'minimum_wage', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'workers', effect: 12 },
      { voterGroup: 'youth', effect: 6 },
      { voterGroup: 'business', effect: -6 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 60, conservative: 30 },
  },
  {
    id: 'bill_flat_tax',
    name: 'Flat Tax Act',
    description: 'Replace progressive income tax with a single flat rate of 20% for all earners.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 30 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 18 },
      { voterGroup: 'workers', effect: -10 },
      { voterGroup: 'retirees', effect: -5 },
      { voterGroup: 'liberals', effect: -8 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 40, conservative: 80 },
  },
  {
    id: 'bill_free_trade',
    name: 'Free Trade Expansion',
    description: 'Eliminate tariffs and open borders to international commerce.',
    category: 'economy',
    policyChanges: [
      { policyId: 'trade_openness', targetValue: 90 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'workers', effect: -8 },
      { voterGroup: 'rural', effect: -10 },
      { voterGroup: 'patriots', effect: -12 },
    ],
    ideologyAlignment: { progressive: 40, centrist: 65, conservative: 50 },
  },
  {
    id: 'bill_protectionism',
    name: 'Trade Protectionism Act',
    description: 'Impose tariffs on foreign goods to protect domestic industries and jobs.',
    category: 'economy',
    policyChanges: [
      { policyId: 'trade_openness', targetValue: 25 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'rural', effect: 8 },
      { voterGroup: 'patriots', effect: 12 },
      { voterGroup: 'business', effect: -15 },
    ],
    ideologyAlignment: { progressive: 25, centrist: 35, conservative: 60 },
  },
  {
    id: 'bill_tech_investment',
    name: 'National Tech Investment Fund',
    description: 'Create a sovereign tech fund to invest in AI, biotech, and green energy startups.',
    category: 'economy',
    policyChanges: [
      { policyId: 'tech_research', targetValue: 80 },
      { policyId: 'govt_spending', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'rural', effect: -3 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 70, conservative: 40 },
  },
  {
    id: 'bill_austerity',
    name: 'Austerity Measures Act',
    description: 'Slash government spending across the board to reduce national debt.',
    category: 'economy',
    policyChanges: [
      { policyId: 'govt_spending', targetValue: 20 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'business', effect: 12 },
      { voterGroup: 'workers', effect: -15 },
      { voterGroup: 'retirees', effect: -12 },
      { voterGroup: 'youth', effect: -8 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 35, conservative: 75 },
  },
  {
    id: 'bill_bank_regulation',
    name: 'Banking Regulation Act',
    description: 'Impose strict regulations on banks including leverage limits and stress tests.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 50 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: -10 },
      { voterGroup: 'liberals', effect: 6 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_bank_moderate',
    name: 'Moderate Banking Oversight',
    description: 'Light-touch regulation with quarterly reporting and voluntary stress tests.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 40 },
    ],
    cost: 1,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'business', effect: 5 },
      { voterGroup: 'workers', effect: 3 },
    ],
    ideologyAlignment: { progressive: 35, centrist: 70, conservative: 50 },
  },
  {
    id: 'bill_bank_deregulation',
    name: 'Banking Deregulation',
    description: 'Remove post-crisis banking regulations to unleash lending and growth.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 20 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 18 },
      { voterGroup: 'workers', effect: -8 },
      { voterGroup: 'liberals', effect: -10 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 30, conservative: 80 },
  },
  {
    id: 'bill_pension_reform',
    name: 'Public Pension Reform',
    description: 'Restructure the pension system: raise retirement age, increase contributions.',
    category: 'economy',
    policyChanges: [
      { policyId: 'pensions', targetValue: 40 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'retirees', effect: -20 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'youth', effect: 5 },
      { voterGroup: 'workers', effect: -5 },
    ],
    ideologyAlignment: { progressive: 15, centrist: 50, conservative: 65 },
  },
  {
    id: 'bill_pension_privatize',
    name: 'Pension Privatization',
    description: 'Allow workers to invest pension contributions in private market accounts.',
    category: 'economy',
    policyChanges: [
      { policyId: 'pensions', targetValue: 25 },
    ],
    cost: 2,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'youth', effect: 3 },
      { voterGroup: 'retirees', effect: -25 },
      { voterGroup: 'workers', effect: -10 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 30, conservative: 75 },
  },
  {
    id: 'bill_pension_expand',
    name: 'Pension Expansion Act',
    description: 'Lower retirement age and increase pension payments by 30%.',
    category: 'economy',
    policyChanges: [
      { policyId: 'pensions', targetValue: 85 },
      { policyId: 'govt_spending', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 25 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'business', effect: -12 },
      { voterGroup: 'youth', effect: -5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 45, conservative: 20 },
  },
  {
    id: 'bill_stimulus',
    name: 'Economic Stimulus Package',
    description: 'Emergency spending to boost consumer demand and create jobs during downturn.',
    category: 'economy',
    policyChanges: [
      { policyId: 'govt_spending', targetValue: 80 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: 12 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: 5 },
      { voterGroup: 'retirees', effect: 3 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 55, conservative: 20 },
  },
  {
    id: 'bill_infrastructure',
    name: 'National Infrastructure Act',
    description: 'Invest $500 billion in roads, bridges, broadband, and public transit over 10 years.',
    category: 'economy',
    policyChanges: [
      { policyId: 'public_transport', targetValue: 75 },
      { policyId: 'govt_spending', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'rural', effect: 12 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'business', effect: 5 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 70, conservative: 40 },
  },
  {
    id: 'bill_small_business',
    name: 'Small Business Support Act',
    description: 'Tax credits, low-interest loans, and reduced regulations for businesses under 50 employees.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 35 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'workers', effect: 5 },
    ],
    ideologyAlignment: { progressive: 35, centrist: 75, conservative: 70 },
  },
  {
    id: 'bill_crypto_regulation',
    name: 'Cryptocurrency Regulation Act',
    description: 'Regulate cryptocurrency exchanges, require KYC, and tax crypto gains.',
    category: 'economy',
    policyChanges: [
      { policyId: 'tech_research', targetValue: 55 },
      { policyId: 'corporate_tax', targetValue: 50 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'youth', effect: -8 },
      { voterGroup: 'business', effect: -5 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 45, centrist: 60, conservative: 50 },
  },
  {
    id: 'bill_stock_tax',
    name: 'Stock Transaction Tax',
    description: 'Tax every stock trade at 0.1% to curb speculation and fund public services.',
    category: 'economy',
    policyChanges: [
      { policyId: 'corporate_tax', targetValue: 55 },
    ],
    cost: 2,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'workers', effect: 6 },
      { voterGroup: 'business', effect: -15 },
      { voterGroup: 'liberals', effect: 5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_capital_gains',
    name: 'Capital Gains Tax Reform',
    description: 'Tax capital gains at the same rate as income — no more preferential treatment.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: -18 },
      { voterGroup: 'liberals', effect: 6 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_estate_tax',
    name: 'Estate Tax Increase',
    description: 'Tax inherited wealth above $5 million at 40% to reduce dynastic inequality.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'business', effect: -15 },
      { voterGroup: 'liberals', effect: 8 },
      { voterGroup: 'retirees', effect: -5 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 35, conservative: 10 },
  },
  {
    id: 'bill_vat_increase',
    name: 'VAT Increase',
    description: 'Raise value-added tax from 15% to 20% to increase government revenue.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 55 },
    ],
    cost: 1,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: -8 },
      { voterGroup: 'retirees', effect: -5 },
      { voterGroup: 'business', effect: -3 },
      { voterGroup: 'rural', effect: -5 },
    ],
    ideologyAlignment: { progressive: 30, centrist: 50, conservative: 40 },
  },
  {
    id: 'bill_vat_cut',
    name: 'VAT Reduction',
    description: 'Cut value-added tax to 10% to reduce consumer prices and boost spending.',
    category: 'economy',
    policyChanges: [
      { policyId: 'income_tax', targetValue: 30 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 20, centrist: 55, conservative: 70 },
  },

  // ===== HEALTHCARE (20 bills) =====
  {
    id: 'bill_universal_healthcare',
    name: 'Universal Healthcare Act',
    description: 'Establish a single-payer national health service covering all citizens.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 95 },
      { policyId: 'govt_spending', targetValue: 70 },
    ],
    cost: 4,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'workers', effect: 20 },
      { voterGroup: 'retirees', effect: 18 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'business', effect: -15 },
      { voterGroup: 'rural', effect: 10 },
    ],
    ideologyAlignment: { progressive: 90, centrist: 50, conservative: 15 },
  },
  {
    id: 'bill_public_option',
    name: 'Public Option Healthcare',
    description: 'Create a government-run insurance plan that competes with private insurers.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 75 },
    ],
    cost: 3,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'workers', effect: 12 },
      { voterGroup: 'retirees', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: -8 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 60, conservative: 25 },
  },
  {
    id: 'bill_private_healthcare_ban',
    name: 'Private Healthcare Ban',
    description: 'Outlaw private healthcare providers to ensure equal access for all.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 100 },
    ],
    cost: 3,
    constitutionalScore: 35,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'business', effect: -25 },
      { voterGroup: 'liberals', effect: -8 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 15, conservative: 5 },
  },
  {
    id: 'bill_mental_health',
    name: 'Mental Health Funding Act',
    description: 'Massively expand mental health services, counseling, and crisis intervention.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'liberals', effect: 10 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'workers', effect: 5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 65, conservative: 35 },
  },
  {
    id: 'bill_drug_pricing',
    name: 'Drug Price Control Act',
    description: 'Cap pharmaceutical prices and allow government bulk purchasing.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 15 },
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'business', effect: -12 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 55, conservative: 20 },
  },
  {
    id: 'bill_health_privatization',
    name: 'Healthcare Privatization',
    description: 'Transition public health services to private providers for efficiency.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 25 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'workers', effect: -15 },
      { voterGroup: 'retirees', effect: -18 },
      { voterGroup: 'rural', effect: -10 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 30, conservative: 70 },
  },
  {
    id: 'bill_hospital_investment',
    name: 'Hospital Modernization Act',
    description: 'Invest $200 billion in new hospitals, equipment, and rural health clinics.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 80 },
      { policyId: 'govt_spending', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'rural', effect: 15 },
      { voterGroup: 'retirees', effect: 10 },
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: -5 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 65, conservative: 35 },
  },
  {
    id: 'bill_medical_research',
    name: 'Medical Research Funding',
    description: 'Double NIH-equivalent funding for cancer, Alzheimer\'s, and rare disease research.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 70 },
      { policyId: 'tech_research', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'urban', effect: 5 },
      { voterGroup: 'business', effect: 3 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 70, conservative: 45 },
  },
  {
    id: 'bill_pandemic_prep',
    name: 'Pandemic Preparedness Act',
    description: 'Stockpile medical supplies, fund vaccine research, and create rapid response teams.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 8 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'urban', effect: 5 },
    ],
    ideologyAlignment: { progressive: 55, centrist: 65, conservative: 50 },
  },
  {
    id: 'bill_longterm_care',
    name: 'Long-Term Care Act',
    description: 'Universal long-term care insurance for elderly and disabled citizens.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 80 },
      { policyId: 'pensions', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 22 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'business', effect: -8 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_dental_coverage',
    name: 'Universal Dental Coverage',
    description: 'Add dental care to the national health service — free cleanings, fillings, and procedures.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'retirees', effect: 12 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 50, conservative: 20 },
  },
  {
    id: 'bill_vision_coverage',
    name: 'Universal Vision Care',
    description: 'Cover eye exams, glasses, and contact lenses under public health insurance.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 72 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'workers', effect: 6 },
    ],
    ideologyAlignment: { progressive: 68, centrist: 48, conservative: 18 },
  },
  {
    id: 'bill_drug_import',
    name: 'Prescription Drug Import Act',
    description: 'Allow importing cheaper medications from verified international pharmacies.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 65 },
      { policyId: 'trade_openness', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'retirees', effect: 12 },
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'business', effect: -10 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 55, conservative: 30 },
  },
  {
    id: 'bill_healthcare_worker_pay',
    name: 'Healthcare Worker Pay Act',
    description: 'Raise salaries for nurses, paramedics, and hospital staff by 25%.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 72 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'workers', effect: 12 },
      { voterGroup: 'retirees', effect: 5 },
      { voterGroup: 'rural', effect: 6 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 60, conservative: 35 },
  },
  {
    id: 'bill_telemedicine',
    name: 'Telemedicine Expansion',
    description: 'Fund broadband infrastructure and platforms for remote medical consultations.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 65 },
      { policyId: 'tech_research', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'rural', effect: 15 },
      { voterGroup: 'retirees', effect: 8 },
      { voterGroup: 'youth', effect: 5 },
    ],
    ideologyAlignment: { progressive: 55, centrist: 70, conservative: 50 },
  },
  {
    id: 'bill_rehab_funding',
    name: 'Addiction Rehabilitation Funding',
    description: 'Triple funding for drug and alcohol rehabilitation centers and outreach programs.',
    category: 'healthcare',
    policyChanges: [
      { policyId: 'healthcare', targetValue: 68 },
      { policyId: 'drug_policy', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 10 },
      { voterGroup: 'rural', effect: 5 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'religious', effect: 3 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 60, conservative: 35 },
  },

  // ===== EDUCATION (20 bills) =====
  {
    id: 'bill_free_university',
    name: 'Free University Education',
    description: 'Abolish tuition fees at all public universities funded by tax revenue.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 90 },
      { policyId: 'govt_spending', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'youth', effect: 25 },
      { voterGroup: 'liberals', effect: 12 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'business', effect: -8 },
      { voterGroup: 'retirees', effect: -3 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 45, conservative: 10 },
  },
  {
    id: 'bill_school_vouchers',
    name: 'School Voucher Program',
    description: 'Give parents vouchers to choose any school, including private institutions.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 45 },
    ],
    cost: 2,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'religious', effect: 15 },
      { voterGroup: 'business', effect: 8 },
      { voterGroup: 'liberals', effect: -10 },
      { voterGroup: 'urban', effect: -5 },
    ],
    ideologyAlignment: { progressive: 15, centrist: 45, conservative: 75 },
  },
  {
    id: 'bill_stem_funding',
    name: 'STEM Education Investment',
    description: 'Triple funding for science, technology, engineering, and mathematics programs.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 75 },
      { policyId: 'tech_research', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'urban', effect: 8 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 75, conservative: 50 },
  },
  {
    id: 'bill_teacher_pay',
    name: 'Teacher Pay Increase Act',
    description: 'Raise teacher salaries by 30% to attract top talent to education.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'rural', effect: 6 },
      { voterGroup: 'liberals', effect: 5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 60, conservative: 35 },
  },
  {
    id: 'bill_vocational_training',
    name: 'Vocational Training Expansion',
    description: 'Fund apprenticeships and trade schools as alternatives to university.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'workers', effect: 12 },
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: 6 },
    ],
    ideologyAlignment: { progressive: 50, centrist: 70, conservative: 60 },
  },
  {
    id: 'bill_student_loan_forgiveness',
    name: 'Student Loan Forgiveness',
    description: 'Cancel up to $50,000 in student debt for qualifying borrowers.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 80 },
      { policyId: 'govt_spending', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'youth', effect: 25 },
      { voterGroup: 'liberals', effect: 12 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'retirees', effect: -10 },
      { voterGroup: 'business', effect: -5 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 35, conservative: 5 },
  },
  {
    id: 'bill_charter_schools',
    name: 'Charter School Expansion',
    description: 'Allow more publicly funded, privately operated charter schools to open.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 55 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'business', effect: 8 },
      { voterGroup: 'religious', effect: 8 },
      { voterGroup: 'liberals', effect: -8 },
      { voterGroup: 'workers', effect: -5 },
    ],
    ideologyAlignment: { progressive: 20, centrist: 50, conservative: 70 },
  },
  {
    id: 'bill_testing_reform',
    name: 'Standardized Testing Reform',
    description: 'Replace high-stakes testing with portfolio-based assessment and teacher evaluations.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 65 },
    ],
    cost: 1,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'liberals', effect: 8 },
      { voterGroup: 'workers', effect: 3 },
      { voterGroup: 'business', effect: -3 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_school_lunch',
    name: 'Universal School Lunch Program',
    description: 'Provide free breakfast and lunch to all K-12 students regardless of income.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'workers', effect: 10 },
      { voterGroup: 'rural', effect: 8 },
      { voterGroup: 'youth', effect: 6 },
      { voterGroup: 'retirees', effect: 3 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 60, conservative: 30 },
  },
  {
    id: 'bill_class_size',
    name: 'Class Size Reduction Act',
    description: 'Cap class sizes at 20 students by hiring more teachers and building new schools.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 75 },
      { policyId: 'govt_spending', targetValue: 60 },
    ],
    cost: 3,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'liberals', effect: 6 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_arts_education',
    name: 'Arts & Music Education Funding',
    description: 'Restore arts and music programs to all public schools with dedicated funding.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'liberals', effect: 10 },
      { voterGroup: 'urban', effect: 6 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 55, conservative: 30 },
  },
  {
    id: 'bill_special_ed',
    name: 'Special Education Funding Act',
    description: 'Triple federal funding for special education services and teacher training.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'liberals', effect: 6 },
      { voterGroup: 'religious', effect: 3 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 65, conservative: 45 },
  },
  {
    id: 'bill_literacy',
    name: 'National Literacy Campaign',
    description: 'Fund adult literacy programs and reading initiatives for underserved communities.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 62 },
    ],
    cost: 1,
    constitutionalScore: 95,
    popularityEffects: [
      { voterGroup: 'workers', effect: 6 },
      { voterGroup: 'rural', effect: 8 },
      { voterGroup: 'liberals', effect: 5 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 65, conservative: 45 },
  },
  {
    id: 'bill_early_childhood',
    name: 'Universal Pre-K Education',
    description: 'Provide free pre-kindergarten for all 3-4 year olds nationwide.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 75 },
      { policyId: 'govt_spending', targetValue: 60 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'workers', effect: 15 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'liberals', effect: 8 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 55, conservative: 20 },
  },
  {
    id: 'bill_coding_curriculum',
    name: 'Digital Literacy Mandate',
    description: 'Make coding and digital skills a core subject from primary school onwards.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 68 },
      { policyId: 'tech_research', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'business', effect: 8 },
      { voterGroup: 'urban', effect: 5 },
    ],
    ideologyAlignment: { progressive: 55, centrist: 70, conservative: 45 },
  },
  {
    id: 'bill_school_safety',
    name: 'School Safety Act',
    description: 'Fund security upgrades, counselors, and mental health support in all schools.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 65 },
      { policyId: 'police', targetValue: 55 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'retirees', effect: 5 },
      { voterGroup: 'patriots', effect: 5 },
      { voterGroup: 'rural', effect: 5 },
    ],
    ideologyAlignment: { progressive: 45, centrist: 65, conservative: 60 },
  },
  {
    id: 'bill_education_privatize',
    name: 'Education Privatization Act',
    description: 'Transfer public school management to private companies for efficiency.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 35 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'workers', effect: -15 },
      { voterGroup: 'liberals', effect: -12 },
      { voterGroup: 'rural', effect: -8 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 70 },
  },
  {
    id: 'bill_history_curriculum',
    name: 'National History Curriculum',
    description: 'Standardize history teaching to include diverse perspectives and critical thinking.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 63 },
    ],
    cost: 1,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 8 },
      { voterGroup: 'youth', effect: 5 },
      { voterGroup: 'patriots', effect: -8 },
      { voterGroup: 'religious', effect: -5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 45, conservative: 20 },
  },
  {
    id: 'bill_research_grants',
    name: 'University Research Grants',
    description: 'Quadruple government research grants for academic institutions.',
    category: 'education',
    policyChanges: [
      { policyId: 'education', targetValue: 72 },
      { policyId: 'tech_research', targetValue: 72 },
    ],
    cost: 3,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: 5 },
      { voterGroup: 'liberals', effect: 5 },
    ],
    ideologyAlignment: { progressive: 60, centrist: 65, conservative: 40 },
  },

  // ===== ENVIRONMENT (15 bills) =====
  {
    id: 'bill_carbon_tax',
    name: 'Carbon Tax Act',
    description: 'Tax carbon emissions at $50/ton, rebating proceeds equally to all citizens.',
    category: 'environment',
    policyChanges: [
      { policyId: 'carbon_tax', targetValue: 80 },
      { policyId: 'env_regulations', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 25 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'business', effect: -18 },
      { voterGroup: 'rural', effect: -12 },
      { voterGroup: 'workers', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_green_new_deal',
    name: 'Green New Deal',
    description: 'Massive investment in renewable energy, green jobs, and emissions reduction.',
    category: 'environment',
    policyChanges: [
      { policyId: 'renewables', targetValue: 95 },
      { policyId: 'env_regulations', targetValue: 85 },
      { policyId: 'govt_spending', targetValue: 75 },
    ],
    cost: 4,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 30 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'business', effect: -20 },
      { voterGroup: 'rural', effect: -10 },
      { voterGroup: 'workers', effect: 5 },
    ],
    ideologyAlignment: { progressive: 90, centrist: 30, conservative: 5 },
  },
  {
    id: 'bill_fracking_ban',
    name: 'Fracking Ban',
    description: 'Permanently ban hydraulic fracturing for oil and gas extraction.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 20 },
      { voterGroup: 'rural', effect: -15 },
      { voterGroup: 'workers', effect: -8 },
      { voterGroup: 'business', effect: -10 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 30, conservative: 10 },
  },
  {
    id: 'bill_wildlife_protection',
    name: 'Wildlife Protection Act',
    description: 'Expand protected areas by 30% and increase penalties for poaching.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 70 },
      { policyId: 'agriculture', targetValue: 40 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 18 },
      { voterGroup: 'rural', effect: -12 },
      { voterGroup: 'liberals', effect: 6 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 55, conservative: 30 },
  },
  {
    id: 'bill_nuclear_energy',
    name: 'Nuclear Energy Expansion',
    description: 'Build 10 new nuclear power plants for clean baseload electricity.',
    category: 'environment',
    policyChanges: [
      { policyId: 'renewables', targetValue: 65 },
      { policyId: 'tech_research', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'environmentalists', effect: -8 },
      { voterGroup: 'rural', effect: -5 },
      { voterGroup: 'youth', effect: 3 },
    ],
    ideologyAlignment: { progressive: 35, centrist: 60, conservative: 55 },
  },
  {
    id: 'bill_renewable_subsidies',
    name: 'Renewable Energy Subsidies',
    description: 'Massive tax credits and subsidies for solar, wind, and geothermal installation.',
    category: 'environment',
    policyChanges: [
      { policyId: 'renewables', targetValue: 85 },
      { policyId: 'govt_spending', targetValue: 60 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 20 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'rural', effect: 3 },
      { voterGroup: 'business', effect: -8 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_ev_mandate',
    name: 'Electric Vehicle Mandate',
    description: 'Ban new fossil fuel car sales by 2035, with subsidies for EV purchases.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 80 },
      { policyId: 'renewables', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 22 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'rural', effect: -18 },
      { voterGroup: 'workers', effect: -5 },
      { voterGroup: 'business', effect: -5 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 35, conservative: 10 },
  },
  {
    id: 'bill_plastic_ban',
    name: 'Single-Use Plastics Ban',
    description: 'Ban single-use plastic bags, straws, cutlery, and packaging nationwide.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 65 },
    ],
    cost: 1,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 15 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: -8 },
      { voterGroup: 'rural', effect: -3 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 50, conservative: 20 },
  },
  {
    id: 'bill_reforestation',
    name: 'National Reforestation Act',
    description: 'Plant 1 billion trees over 10 years and restore degraded forests.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 18 },
      { voterGroup: 'rural', effect: 5 },
      { voterGroup: 'youth', effect: 8 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 65, conservative: 40 },
  },
  {
    id: 'bill_water_protection',
    name: 'Clean Water Protection Act',
    description: 'Strict regulations on industrial water pollution and pesticide runoff.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 72 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 15 },
      { voterGroup: 'rural', effect: 5 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'business', effect: -8 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 60, conservative: 35 },
  },
  {
    id: 'bill_air_quality',
    name: 'Air Quality Standards Act',
    description: 'Tighten emissions standards for factories, power plants, and vehicles.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 82,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 15 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'business', effect: -12 },
      { voterGroup: 'workers', effect: -3 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_climate_adaptation',
    name: 'Climate Adaptation Fund',
    description: 'Invest in flood defenses, drought preparation, and climate-resilient infrastructure.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 60 },
      { policyId: 'govt_spending', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 10 },
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'workers', effect: 5 },
    ],
    ideologyAlignment: { progressive: 55, centrist: 65, conservative: 40 },
  },
  {
    id: 'bill_carbon_capture',
    name: 'Carbon Capture Investment',
    description: 'Fund development of carbon capture and storage technology at industrial scale.',
    category: 'environment',
    policyChanges: [
      { policyId: 'tech_research', targetValue: 70 },
      { policyId: 'env_regulations', targetValue: 55 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'business', effect: 8 },
      { voterGroup: 'environmentalists', effect: 5 },
      { voterGroup: 'youth', effect: 5 },
    ],
    ideologyAlignment: { progressive: 45, centrist: 65, conservative: 55 },
  },
  {
    id: 'bill_env_deregulation',
    name: 'Environmental Deregulation',
    description: 'Roll back environmental regulations to boost economic growth and job creation.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 20 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'business', effect: 18 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'environmentalists', effect: -25 },
      { voterGroup: 'youth', effect: -10 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 75 },
  },
  {
    id: 'bill_circular_economy',
    name: 'Circular Economy Act',
    description: 'Mandate recycling targets, product repair rights, and extended producer responsibility.',
    category: 'environment',
    policyChanges: [
      { policyId: 'env_regulations', targetValue: 68 },
    ],
    cost: 2,
    constitutionalScore: 82,
    popularityEffects: [
      { voterGroup: 'environmentalists', effect: 12 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: -10 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 55, conservative: 25 },
  },

  // ===== SECURITY (15 bills) =====
  {
    id: 'bill_police_reform',
    name: 'Police Reform Act',
    description: 'Mandate body cameras, de-escalation training, and civilian oversight boards.',
    category: 'security',
    policyChanges: [
      { policyId: 'police', targetValue: 55 },
      { policyId: 'civil_rights', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'patriots', effect: -10 },
      { voterGroup: 'religious', effect: -3 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 50, conservative: 15 },
  },
  {
    id: 'bill_surveillance',
    name: 'National Surveillance Act',
    description: 'Expand electronic surveillance powers for intelligence agencies.',
    category: 'security',
    policyChanges: [
      { policyId: 'intelligence', targetValue: 85 },
      { policyId: 'civil_rights', targetValue: 30 },
    ],
    cost: 2,
    constitutionalScore: 30,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 12 },
      { voterGroup: 'liberals', effect: -20 },
      { voterGroup: 'youth', effect: -10 },
      { voterGroup: 'religious', effect: 3 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 35, conservative: 70 },
  },
  {
    id: 'bill_gun_control',
    name: 'Comprehensive Gun Control',
    description: 'Ban assault weapons, require background checks and licensing for all firearms.',
    category: 'security',
    policyChanges: [
      { policyId: 'gun_control', targetValue: 85 },
    ],
    cost: 2,
    constitutionalScore: 45,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'rural', effect: -18 },
      { voterGroup: 'patriots', effect: -15 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 45, conservative: 10 },
  },
  {
    id: 'bill_gun_moderate',
    name: 'Universal Background Checks',
    description: 'Require background checks for all gun sales including private transactions.',
    category: 'security',
    policyChanges: [
      { policyId: 'gun_control', targetValue: 60 },
    ],
    cost: 1,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 8 },
      { voterGroup: 'urban', effect: 5 },
      { voterGroup: 'rural', effect: -5 },
      { voterGroup: 'patriots', effect: -8 },
    ],
    ideologyAlignment: { progressive: 55, centrist: 65, conservative: 30 },
  },
  {
    id: 'bill_gun_rights',
    name: 'Gun Rights Expansion',
    description: 'Expand concealed carry permits, reduce waiting periods, and preempt local gun laws.',
    category: 'security',
    policyChanges: [
      { policyId: 'gun_control', targetValue: 15 },
    ],
    cost: 2,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 20 },
      { voterGroup: 'rural', effect: 12 },
      { voterGroup: 'liberals', effect: -18 },
      { voterGroup: 'urban', effect: -10 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 85 },
  },
  {
    id: 'bill_military_expansion',
    name: 'Military Modernization Act',
    description: 'Double the defense budget to modernize armed forces and expand capabilities.',
    category: 'security',
    policyChanges: [
      { policyId: 'military', targetValue: 85 },
      { policyId: 'govt_spending', targetValue: 70 },
    ],
    cost: 3,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 22 },
      { voterGroup: 'business', effect: 5 },
      { voterGroup: 'environmentalists', effect: -8 },
      { voterGroup: 'liberals', effect: -10 },
      { voterGroup: 'workers', effect: -3 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 40, conservative: 85 },
  },
  {
    id: 'bill_military_cuts',
    name: 'Defense Spending Reduction',
    description: 'Cut military budget by 30% and redirect funds to social programs.',
    category: 'security',
    policyChanges: [
      { policyId: 'military', targetValue: 30 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 12 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'patriots', effect: -22 },
      { voterGroup: 'rural', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 35, conservative: 5 },
  },
  {
    id: 'bill_cyber_defense',
    name: 'Cyber Defense Initiative',
    description: 'Create a national cyber defense force to protect critical infrastructure.',
    category: 'security',
    policyChanges: [
      { policyId: 'intelligence', targetValue: 70 },
      { policyId: 'tech_research', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 82,
    popularityEffects: [
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'business', effect: 10 },
      { voterGroup: 'patriots', effect: 8 },
    ],
    ideologyAlignment: { progressive: 45, centrist: 70, conservative: 65 },
  },
  {
    id: 'bill_border_security_increase',
    name: 'Border Security Enhancement',
    description: 'Fund drones, sensors, and personnel to secure national borders.',
    category: 'security',
    policyChanges: [
      { policyId: 'border_security', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 18 },
      { voterGroup: 'rural', effect: 8 },
      { voterGroup: 'liberals', effect: -10 },
      { voterGroup: 'youth', effect: -5 },
    ],
    ideologyAlignment: { progressive: 15, centrist: 45, conservative: 75 },
  },
  {
    id: 'bill_intelligence_funding',
    name: 'Intelligence Services Expansion',
    description: 'Increase funding for intelligence agencies by 50% with enhanced oversight.',
    category: 'security',
    policyChanges: [
      { policyId: 'intelligence', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 10 },
      { voterGroup: 'liberals', effect: -8 },
      { voterGroup: 'youth', effect: -5 },
    ],
    ideologyAlignment: { progressive: 20, centrist: 50, conservative: 70 },
  },
  {
    id: 'bill_veteran_benefits',
    name: 'Veterans Benefits Expansion',
    description: 'Expand healthcare, housing, and job training programs for military veterans.',
    category: 'security',
    policyChanges: [
      { policyId: 'military', targetValue: 60 },
      { policyId: 'healthcare', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 15 },
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'rural', effect: 8 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 45, centrist: 70, conservative: 75 },
  },
  {
    id: 'bill_emergency_response',
    name: 'National Emergency Response Act',
    description: 'Create rapid-response teams and stockpile supplies for natural disasters.',
    category: 'security',
    policyChanges: [
      { policyId: 'police', targetValue: 55 },
    ],
    cost: 2,
    constitutionalScore: 90,
    popularityEffects: [
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'retirees', effect: 5 },
    ],
    ideologyAlignment: { progressive: 50, centrist: 70, conservative: 55 },
  },
  {
    id: 'bill_counter_terrorism',
    name: 'Counter-Terrorism Act',
    description: 'Expand anti-terrorism powers including preventive detention and asset freezing.',
    category: 'security',
    policyChanges: [
      { policyId: 'intelligence', targetValue: 80 },
      { policyId: 'civil_rights', targetValue: 40 },
    ],
    cost: 2,
    constitutionalScore: 40,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 15 },
      { voterGroup: 'liberals', effect: -18 },
      { voterGroup: 'youth', effect: -8 },
      { voterGroup: 'religious', effect: -5 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 40, conservative: 75 },
  },
  {
    id: 'bill_police_funding',
    name: 'Police Funding Increase',
    description: 'Increase police budgets by 25% for more officers and better equipment.',
    category: 'security',
    policyChanges: [
      { policyId: 'police', targetValue: 75 },
    ],
    cost: 2,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 12 },
      { voterGroup: 'retirees', effect: 8 },
      { voterGroup: 'liberals', effect: -10 },
      { voterGroup: 'youth', effect: -8 },
    ],
    ideologyAlignment: { progressive: 15, centrist: 45, conservative: 75 },
  },
  {
    id: 'bill_defund_police',
    name: 'Redirect Police Funding',
    description: 'Redirect 40% of police budgets to social workers, mental health, and community programs.',
    category: 'security',
    policyChanges: [
      { policyId: 'police', targetValue: 30 },
      { policyId: 'civil_rights', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'patriots', effect: -20 },
      { voterGroup: 'retirees', effect: -12 },
      { voterGroup: 'rural', effect: -8 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 25, conservative: 5 },
  },

  // ===== SOCIAL (15 bills) =====
  {
    id: 'bill_marriage_equality',
    name: 'Marriage Equality Act',
    description: 'Legalize same-sex marriage nationwide with full equal rights.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 80 },
    ],
    cost: 1,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 20 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'religious', effect: -20 },
      { voterGroup: 'rural', effect: -8 },
    ],
    ideologyAlignment: { progressive: 90, centrist: 55, conservative: 10 },
  },
  {
    id: 'bill_drug_decriminalization',
    name: 'Drug Decriminalization',
    description: 'Decriminalize personal drug use, redirect funding to treatment programs.',
    category: 'social',
    policyChanges: [
      { policyId: 'drug_policy', targetValue: 80 },
      { policyId: 'civil_rights', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'religious', effect: -15 },
      { voterGroup: 'patriots', effect: -12 },
      { voterGroup: 'rural', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 35, conservative: 5 },
  },
  {
    id: 'bill_abortion_rights',
    name: 'Reproductive Rights Act',
    description: 'Enshrine abortion access as a protected right in national law.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 50,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 20 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'religious', effect: -25 },
      { voterGroup: 'rural', effect: -8 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 40, conservative: 5 },
  },
  {
    id: 'bill_press_protection',
    name: 'Press Freedom Protection',
    description: 'Shield journalists from prosecution and mandate government transparency.',
    category: 'social',
    policyChanges: [
      { policyId: 'press_freedom', targetValue: 90 },
    ],
    cost: 1,
    constitutionalScore: 92,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'urban', effect: 5 },
      { voterGroup: 'patriots', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 65, conservative: 30 },
  },
  {
    id: 'bill_traditional_values',
    name: 'Traditional Values Act',
    description: 'Promote traditional family structures through tax breaks and education policy.',
    category: 'social',
    policyChanges: [
      { policyId: 'religious_freedom', targetValue: 80 },
      { policyId: 'civil_rights', targetValue: 35 },
    ],
    cost: 2,
    constitutionalScore: 50,
    popularityEffects: [
      { voterGroup: 'religious', effect: 22 },
      { voterGroup: 'rural', effect: 12 },
      { voterGroup: 'retirees', effect: 8 },
      { voterGroup: 'liberals', effect: -18 },
      { voterGroup: 'youth', effect: -15 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 85 },
  },
  {
    id: 'bill_religious_freedom',
    name: 'Religious Freedom Restoration',
    description: 'Protect the right to practice any religion and exempt religious institutions from certain regulations.',
    category: 'social',
    policyChanges: [
      { policyId: 'religious_freedom', targetValue: 85 },
    ],
    cost: 1,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'religious', effect: 20 },
      { voterGroup: 'rural', effect: 5 },
      { voterGroup: 'liberals', effect: -8 },
      { voterGroup: 'youth', effect: -5 },
    ],
    ideologyAlignment: { progressive: 20, centrist: 45, conservative: 75 },
  },
  {
    id: 'bill_lgbtq_protections',
    name: 'LGBTQ+ Anti-Discrimination Act',
    description: 'Ban discrimination based on sexual orientation and gender identity in employment, housing, and services.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 82 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 15 },
      { voterGroup: 'urban', effect: 8 },
      { voterGroup: 'religious', effect: -15 },
      { voterGroup: 'rural', effect: -5 },
    ],
    ideologyAlignment: { progressive: 85, centrist: 50, conservative: 10 },
  },
  {
    id: 'bill_hate_crime',
    name: 'Hate Crime Enhancement Act',
    description: 'Stiffer penalties for crimes motivated by race, religion, gender, or sexual orientation.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 72 },
      { policyId: 'police', targetValue: 55 },
    ],
    cost: 1,
    constitutionalScore: 78,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 12 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'religious', effect: -3 },
      { voterGroup: 'patriots', effect: -5 },
    ],
    ideologyAlignment: { progressive: 70, centrist: 55, conservative: 25 },
  },
  {
    id: 'bill_death_penalty_abolition',
    name: 'Death Penalty Abolition',
    description: 'Permanently abolish capital punishment and replace with life imprisonment.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 78 },
    ],
    cost: 1,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'religious', effect: 3 },
      { voterGroup: 'patriots', effect: -15 },
      { voterGroup: 'rural', effect: -8 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 45, conservative: 10 },
  },
  {
    id: 'bill_voting_rights',
    name: 'Voting Rights Expansion',
    description: 'Automatic voter registration, mail-in voting, and making election day a national holiday.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'workers', effect: 8 },
      { voterGroup: 'patriots', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 55, conservative: 15 },
  },
  {
    id: 'bill_prison_reform',
    name: 'Prison Reform Act',
    description: 'Reduce mandatory minimums, expand rehabilitation, and ban private prisons.',
    category: 'social',
    policyChanges: [
      { policyId: 'civil_rights', targetValue: 75 },
      { policyId: 'police', targetValue: 45 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'workers', effect: 5 },
      { voterGroup: 'patriots', effect: -12 },
      { voterGroup: 'retirees', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_cannabis_legalization',
    name: 'Cannabis Legalization',
    description: 'Fully legalize recreational cannabis, tax sales, and expunge prior convictions.',
    category: 'social',
    policyChanges: [
      { policyId: 'drug_policy', targetValue: 75 },
      { policyId: 'civil_rights', targetValue: 68 },
    ],
    cost: 2,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'youth', effect: 18 },
      { voterGroup: 'liberals', effect: 12 },
      { voterGroup: 'business', effect: 5 },
      { voterGroup: 'religious', effect: -12 },
      { voterGroup: 'retirees', effect: -8 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 45, conservative: 10 },
  },
  {
    id: 'bill_censorship',
    name: 'Content Regulation Act',
    description: 'Government oversight of media and internet content to combat misinformation.',
    category: 'social',
    policyChanges: [
      { policyId: 'press_freedom', targetValue: 30 },
      { policyId: 'civil_rights', targetValue: 35 },
    ],
    cost: 2,
    constitutionalScore: 25,
    popularityEffects: [
      { voterGroup: 'liberals', effect: -20 },
      { voterGroup: 'youth', effect: -15 },
      { voterGroup: 'religious', effect: 8 },
      { voterGroup: 'patriots', effect: 5 },
    ],
    ideologyAlignment: { progressive: 10, centrist: 20, conservative: 55 },
  },
  {
    id: 'bill_housing_right',
    name: 'Right to Housing Act',
    description: 'Enshrine housing as a fundamental right, expand public housing and rent controls.',
    category: 'social',
    policyChanges: [
      { policyId: 'housing_subsidies', targetValue: 85 },
      { policyId: 'govt_spending', targetValue: 65 },
    ],
    cost: 3,
    constitutionalScore: 65,
    popularityEffects: [
      { voterGroup: 'workers', effect: 15 },
      { voterGroup: 'youth', effect: 12 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'business', effect: -12 },
      { voterGroup: 'rural', effect: 3 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_whistleblower',
    name: 'Whistleblower Protection Act',
    description: 'Strong legal protections and rewards for whistleblowers exposing government or corporate wrongdoing.',
    category: 'social',
    policyChanges: [
      { policyId: 'press_freedom', targetValue: 75 },
      { policyId: 'civil_rights', targetValue: 70 },
    ],
    cost: 1,
    constitutionalScore: 85,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 12 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'workers', effect: 5 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 60, conservative: 30 },
  },

  // ===== IMMIGRATION (10 bills) =====
  {
    id: 'bill_border_wall',
    name: 'Border Wall Construction',
    description: 'Build a fortified border wall and increase border patrol staffing.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'border_security', targetValue: 90 },
      { policyId: 'immigration', targetValue: 15 },
    ],
    cost: 3,
    constitutionalScore: 70,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 25 },
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'liberals', effect: -20 },
      { voterGroup: 'youth', effect: -8 },
      { voterGroup: 'business', effect: -5 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 85 },
  },
  {
    id: 'bill_path_citizenship',
    name: 'Path to Citizenship',
    description: 'Create a legal pathway to citizenship for undocumented residents.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 80 },
      { policyId: 'civil_rights', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 60,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 18 },
      { voterGroup: 'youth', effect: 10 },
      { voterGroup: 'workers', effect: 3 },
      { voterGroup: 'patriots', effect: -20 },
      { voterGroup: 'rural', effect: -10 },
      { voterGroup: 'religious', effect: -5 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_refugee_program',
    name: 'Refugee Resettlement Program',
    description: 'Expand refugee intake by 200% and provide integration support services.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 85 },
      { policyId: 'foreign_aid', targetValue: 65 },
    ],
    cost: 2,
    constitutionalScore: 75,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'religious', effect: 5 },
      { voterGroup: 'patriots', effect: -18 },
      { voterGroup: 'rural', effect: -10 },
    ],
    ideologyAlignment: { progressive: 75, centrist: 40, conservative: 10 },
  },
  {
    id: 'bill_work_visa',
    name: 'Work Visa Reform',
    description: 'Streamline work visa process, increase quotas, and create fast-track for critical industries.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 70 },
    ],
    cost: 2,
    constitutionalScore: 80,
    popularityEffects: [
      { voterGroup: 'business', effect: 15 },
      { voterGroup: 'youth', effect: 5 },
      { voterGroup: 'workers', effect: -5 },
      { voterGroup: 'patriots', effect: -8 },
    ],
    ideologyAlignment: { progressive: 50, centrist: 65, conservative: 35 },
  },
  {
    id: 'bill_deportation',
    name: 'Strict Deportation Policy',
    description: 'Expedite deportation of undocumented immigrants and visa overstayers.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 20 },
      { policyId: 'border_security', targetValue: 80 },
    ],
    cost: 2,
    constitutionalScore: 55,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 20 },
      { voterGroup: 'rural', effect: 8 },
      { voterGroup: 'liberals', effect: -22 },
      { voterGroup: 'youth', effect: -10 },
      { voterGroup: 'workers', effect: -3 },
    ],
    ideologyAlignment: { progressive: 5, centrist: 25, conservative: 80 },
  },
  {
    id: 'bill_sanctuary',
    name: 'Sanctuary Cities Protection',
    description: 'Protect cities that refuse to enforce federal immigration detainers.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 75 },
      { policyId: 'civil_rights', targetValue: 72 },
    ],
    cost: 2,
    constitutionalScore: 50,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 15 },
      { voterGroup: 'urban', effect: 10 },
      { voterGroup: 'youth', effect: 8 },
      { voterGroup: 'patriots', effect: -18 },
      { voterGroup: 'rural', effect: -12 },
    ],
    ideologyAlignment: { progressive: 80, centrist: 30, conservative: 5 },
  },
  {
    id: 'bill_immigration_courts',
    name: 'Immigration Court Reform',
    description: 'Hire more immigration judges to clear backlogs and ensure fair hearings.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 55 },
    ],
    cost: 2,
    constitutionalScore: 88,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 8 },
      { voterGroup: 'workers', effect: 3 },
      { voterGroup: 'patriots', effect: -3 },
    ],
    ideologyAlignment: { progressive: 55, centrist: 65, conservative: 40 },
  },
  {
    id: 'bill_family_reunification',
    name: 'Family Reunification Act',
    description: 'Prioritize family-based immigration and speed up visa processing for relatives.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 72 },
    ],
    cost: 2,
    constitutionalScore: 78,
    popularityEffects: [
      { voterGroup: 'liberals', effect: 10 },
      { voterGroup: 'religious', effect: 8 },
      { voterGroup: 'workers', effect: 3 },
      { voterGroup: 'patriots', effect: -10 },
    ],
    ideologyAlignment: { progressive: 65, centrist: 50, conservative: 20 },
  },
  {
    id: 'bill_skilled_worker',
    name: 'Skilled Worker Visa Expansion',
    description: 'Double H-1B equivalent visas for tech workers, engineers, and scientists.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 65 },
      { policyId: 'tech_research', targetValue: 60 },
    ],
    cost: 2,
    constitutionalScore: 82,
    popularityEffects: [
      { voterGroup: 'business', effect: 18 },
      { voterGroup: 'youth', effect: 5 },
      { voterGroup: 'workers', effect: -8 },
      { voterGroup: 'patriots', effect: -5 },
    ],
    ideologyAlignment: { progressive: 45, centrist: 70, conservative: 45 },
  },
  {
    id: 'bill_immigration_ban',
    name: 'Immigration Moratorium',
    description: 'Temporary halt to all immigration for 2 years to assess national capacity.',
    category: 'immigration',
    policyChanges: [
      { policyId: 'immigration', targetValue: 5 },
      { policyId: 'border_security', targetValue: 85 },
    ],
    cost: 3,
    constitutionalScore: 35,
    popularityEffects: [
      { voterGroup: 'patriots', effect: 22 },
      { voterGroup: 'rural', effect: 10 },
      { voterGroup: 'liberals', effect: -25 },
      { voterGroup: 'youth', effect: -12 },
      { voterGroup: 'business', effect: -15 },
    ],
    ideologyAlignment: { progressive: 3, centrist: 15, conservative: 80 },
  },
];

export const BILL_CATEGORIES = [
  { id: 'economy', name: 'Economy', icon: '💰' },
  { id: 'healthcare', name: 'Healthcare', icon: '🏥' },
  { id: 'education', name: 'Education', icon: '🎓' },
  { id: 'environment', name: 'Environment', icon: '🌿' },
  { id: 'security', name: 'Security', icon: '🛡️' },
  { id: 'social', name: 'Social', icon: '⚖️' },
  { id: 'immigration', name: 'Immigration', icon: '🌍' },
] as const;

export function getBillTemplate(id: string): BillTemplate | undefined {
  return BILL_LIBRARY.find(b => b.id === id);
}

export function getBillsByCategory(category: string): BillTemplate[] {
  return BILL_LIBRARY.filter(b => b.category === category);
}
