import { RegionDefinition } from './types';

export const REGIONS: RegionDefinition[] = [
  {
    id: 'capitalis',
    name: 'Capitalis',
    description: 'The capital region — urban, wealthy, and cosmopolitan. Financial center, tech hub, and seat of government.',
    populationShare: 0.25,
    seats: 25,
    economicLean: 55,
    socialLean: 75,
    dominantGroups: ['urban', 'business', 'liberals', 'youth'],
    characteristics: 'Financial hub, tech startups, cultural center',
    keyIssues: ['Housing costs', 'Public transport', 'Tech economy', 'Civil liberties'],
    policyWeights: {
      urban_dev: 2.0, public_transport: 1.8, housing_subsidies: 1.6,
      tech_research: 1.5, civil_rights: 1.5, press_freedom: 1.4, corporate_tax: 1.3,
    },
    demographics: {
      populationMillions: 3.2,
      ageYoung: 28, ageMiddle: 45, ageElderly: 27,
      voterGroupBreakdown: {
        urban: 25, liberals: 18, business: 16, youth: 15, workers: 12,
        environmentalists: 6, retirees: 8,
      },
      avgIncome: 'high',
      baseUnemployment: 5.2,
      universityEducated: 52,
      religiousPopulation: 18,
      urbanPercent: 95,
      keyIndustry: 'Finance & Technology',
    },
  },
  {
    id: 'nordmark',
    name: 'Nordmark',
    description: 'Industrial heartland — factories, unions, and working-class pride. The rust belt of Novaria.',
    populationShare: 0.20,
    seats: 20,
    economicLean: 30,
    socialLean: 45,
    dominantGroups: ['workers', 'retirees', 'urban'],
    characteristics: 'Heavy industry, manufacturing, strong unions',
    keyIssues: ['Factory jobs', 'Workers rights', 'Healthcare', 'Pensions'],
    policyWeights: {
      minimum_wage: 2.0, unemployment_benefits: 1.8, healthcare: 1.7,
      pensions: 1.6, education: 1.3, trade_openness: 1.5,
    },
    demographics: {
      populationMillions: 2.5,
      ageYoung: 20, ageMiddle: 40, ageElderly: 40,
      voterGroupBreakdown: {
        workers: 35, retirees: 25, urban: 12, youth: 8, religious: 6,
        patriots: 6, business: 4, liberals: 4,
      },
      avgIncome: 'medium',
      baseUnemployment: 9.5,
      universityEducated: 22,
      religiousPopulation: 30,
      urbanPercent: 70,
      keyIndustry: 'Manufacturing & Heavy Industry',
    },
  },
  {
    id: 'sudfeld',
    name: 'Sudfeld',
    description: 'Southern agricultural heartland — traditional values, farming communities, and vineyards.',
    populationShare: 0.18,
    seats: 18,
    economicLean: 60,
    socialLean: 30,
    dominantGroups: ['rural', 'religious', 'retirees'],
    characteristics: 'Farmland, vineyards, traditional culture',
    keyIssues: ['Agriculture subsidies', 'Religious values', 'Immigration control', 'Rural infrastructure'],
    policyWeights: {
      agriculture: 2.5, religious_freedom: 2.0, immigration: 1.8,
      border_security: 1.6, roads_rail: 1.5, gun_control: 1.3,
    },
    demographics: {
      populationMillions: 2.3,
      ageYoung: 16, ageMiddle: 38, ageElderly: 46,
      voterGroupBreakdown: {
        rural: 30, religious: 22, retirees: 20, workers: 10,
        patriots: 8, business: 5, environmentalists: 3, liberals: 2,
      },
      avgIncome: 'low',
      baseUnemployment: 7.8,
      universityEducated: 15,
      religiousPopulation: 62,
      urbanPercent: 25,
      keyIndustry: 'Agriculture & Viticulture',
    },
  },
  {
    id: 'ostwald',
    name: 'Ostwald',
    description: 'Eastern swing region — diverse economy, university towns, politically unpredictable.',
    populationShare: 0.15,
    seats: 15,
    economicLean: 50,
    socialLean: 50,
    dominantGroups: ['workers', 'youth', 'business'],
    characteristics: 'Mixed economy, university towns, diverse demographics',
    keyIssues: ['Education', 'Employment', 'Development', 'Healthcare'],
    policyWeights: {
      education: 1.8, healthcare: 1.5, govt_spending: 1.4,
      tech_research: 1.3, unemployment_benefits: 1.3,
    },
    demographics: {
      populationMillions: 1.9,
      ageYoung: 30, ageMiddle: 42, ageElderly: 28,
      voterGroupBreakdown: {
        youth: 22, workers: 20, business: 12, urban: 12, liberals: 10,
        retirees: 10, environmentalists: 8, religious: 6,
      },
      avgIncome: 'medium',
      baseUnemployment: 8.1,
      universityEducated: 38,
      religiousPopulation: 25,
      urbanPercent: 55,
      keyIndustry: 'Education & Mixed Services',
    },
  },
  {
    id: 'westhafen',
    name: 'Westhafen',
    description: 'Western coastal region — major port city, international trade hub, shipping industry.',
    populationShare: 0.13,
    seats: 13,
    economicLean: 65,
    socialLean: 60,
    dominantGroups: ['business', 'liberals', 'workers'],
    characteristics: 'Major port city, international trade, shipping industry',
    keyIssues: ['Trade agreements', 'Port infrastructure', 'Foreign policy', 'Environment'],
    policyWeights: {
      trade_openness: 2.5, foreign_aid: 1.5, roads_rail: 1.4,
      env_regulations: 1.3, corporate_tax: 1.5, immigration: 1.2,
    },
    demographics: {
      populationMillions: 1.6,
      ageYoung: 25, ageMiddle: 48, ageElderly: 27,
      voterGroupBreakdown: {
        business: 22, workers: 18, liberals: 15, urban: 15, youth: 10,
        environmentalists: 8, retirees: 8, patriots: 4,
      },
      avgIncome: 'high',
      baseUnemployment: 4.8,
      universityEducated: 40,
      religiousPopulation: 20,
      urbanPercent: 85,
      keyIndustry: 'Trade & Shipping',
    },
  },
  {
    id: 'bergland',
    name: 'Bergland',
    description: 'Mountainous rural region — traditional, self-reliant, and proud. Mining, timber, and tourism.',
    populationShare: 0.09,
    seats: 9,
    economicLean: 55,
    socialLean: 25,
    dominantGroups: ['rural', 'religious', 'patriots'],
    characteristics: 'Mountain villages, mining, timber, tourism',
    keyIssues: ['Agriculture', 'Military/defense', 'Traditional values', 'Border security'],
    policyWeights: {
      agriculture: 2.0, military: 1.8, border_security: 1.7,
      religious_freedom: 1.6, env_regulations: 1.5, gun_control: 1.5, immigration: 1.4,
    },
    demographics: {
      populationMillions: 1.1,
      ageYoung: 14, ageMiddle: 36, ageElderly: 50,
      voterGroupBreakdown: {
        rural: 28, religious: 20, patriots: 18, retirees: 16,
        workers: 10, business: 4, environmentalists: 2, liberals: 2,
      },
      avgIncome: 'low',
      baseUnemployment: 11.2,
      universityEducated: 12,
      religiousPopulation: 70,
      urbanPercent: 15,
      keyIndustry: 'Mining, Timber & Tourism',
    },
  },
];

export const REGION_MAP = new Map(REGIONS.map(r => [r.id, r]));
