import { SituationDefinition, SimulationState, BudgetState } from './types';

export const SITUATIONS: SituationDefinition[] = [
  // ===== ECONOMIC =====
  {
    id: 'debt_crisis',
    name: 'Debt Crisis',
    description: 'National debt has spiraled out of control. Creditors are demanding austerity.',
    icon: '💸',
    category: 'economic',
    severity: 'critical',
    // Triggers when debt > 150% GDP AND deficit > 5% of GDP (~22.5B on 450B base)
    triggerCondition: (_p, sim, _turns, budget) =>
      (budget?.debtToGdp ?? 0) > 150 && (budget?.deficit ?? 0) > (450 * (1 + sim.gdpGrowth / 100)) * 0.05,
    effects: { gdpGrowth: -2, unemployment: 3, inflation: 2 },
    voterEffects: { business: -15, workers: -10 },
    cascades: ['brain_drain'],
  },
  {
    id: 'economic_boom',
    name: 'Economic Boom',
    description: 'The economy is thriving! Growth exceeds expectations.',
    icon: '🚀',
    category: 'economic',
    severity: 'mild',
    triggerCondition: (_p, sim) => sim.gdpGrowth > 4,
    effects: { unemployment: -3, equality: -5 },
    voterEffects: { business: 15, workers: 5, youth: 5 },
  },
  {
    id: 'housing_crisis',
    name: 'Housing Crisis',
    description: 'Skyrocketing rents and insufficient housing stock plague urban areas.',
    icon: '🏚️',
    category: 'economic',
    severity: 'severe',
    triggerCondition: (p) => (p.urban_dev ?? 50) < 35 && (p.housing_subsidies ?? 50) < 30,
    effects: { equality: -10, healthIndex: -5 },
    voterEffects: { youth: -15, urban: -20, workers: -10 },
    cascades: ['homelessness'],
  },
  {
    id: 'brain_drain',
    name: 'Brain Drain',
    description: 'Skilled workers and graduates are leaving the country in droves.',
    icon: '✈️',
    category: 'economic',
    severity: 'moderate',
    triggerCondition: (p, sim) => sim.educationIndex > 60 && (p.income_tax ?? 40) > 65 && sim.gdpGrowth < 1,
    effects: { gdpGrowth: -1, educationIndex: -5 },
    voterEffects: { youth: -10, business: -10 },
  },
  {
    id: 'tech_boom',
    name: 'Tech Boom',
    description: 'A thriving tech sector is driving innovation and creating high-value jobs.',
    icon: '💻',
    category: 'economic',
    severity: 'mild',
    triggerCondition: (p) => (p.tech_research ?? 35) > 70 && (p.education ?? 50) > 60,
    effects: { gdpGrowth: 2, unemployment: -2 },
    voterEffects: { youth: 10, business: 15, urban: 10 },
  },
  {
    id: 'trade_deficit',
    name: 'Trade Deficit',
    description: 'Imports far exceed exports, weakening the domestic economy.',
    icon: '📦',
    category: 'economic',
    severity: 'moderate',
    triggerCondition: (p) => (p.trade_openness ?? 60) > 75 && (p.agriculture ?? 35) < 25,
    effects: { gdpGrowth: -1.5, unemployment: 2 },
    voterEffects: { workers: -10, rural: -10 },
  },
  {
    id: 'hyperinflation',
    name: 'Hyperinflation',
    description: 'Prices are rising uncontrollably. The currency is losing value daily.',
    icon: '📈',
    category: 'economic',
    severity: 'critical',
    triggerCondition: (_p, sim) => sim.inflation > 12,
    effects: { gdpGrowth: -3, equality: -15, crime: 10 },
    voterEffects: { retirees: -20, workers: -15, business: -15 },
    cascades: ['debt_crisis'],
  },
  // ===== SOCIAL =====
  {
    id: 'homelessness',
    name: 'Homelessness Epidemic',
    description: 'Thousands are sleeping rough. Tent cities are appearing in major urban areas.',
    icon: '🏕️',
    category: 'social',
    severity: 'severe',
    triggerCondition: (p, sim) => (p.housing_subsidies ?? 30) < 25 && sim.unemployment > 12,
    effects: { crime: 8, healthIndex: -10 },
    voterEffects: { liberals: -15, urban: -15, religious: -5 },
  },
  {
    id: 'obesity_epidemic',
    name: 'Obesity Epidemic',
    description: 'Poor public health is leading to rising obesity rates and associated diseases.',
    icon: '🍔',
    category: 'social',
    severity: 'moderate',
    triggerCondition: (p) => (p.healthcare ?? 50) < 30,
    effects: { healthIndex: -15 },
    voterEffects: { retirees: -10 },
  },
  {
    id: 'drug_epidemic',
    name: 'Drug Epidemic',
    description: 'Drug abuse is reaching crisis levels across communities.',
    icon: '💊',
    category: 'social',
    severity: 'severe',
    triggerCondition: (p) => (p.drug_policy ?? 30) < 15 || (p.drug_policy ?? 30) > 85,
    effects: { crime: 10, healthIndex: -10 },
    voterEffects: { religious: -15, retirees: -10, rural: -10 },
  },
  {
    id: 'religious_tension',
    name: 'Religious Tensions',
    description: 'Interfaith conflicts are destabilizing communities.',
    icon: '⛪',
    category: 'social',
    severity: 'moderate',
    triggerCondition: (p) => (p.religious_freedom ?? 70) < 25 || (p.religious_freedom ?? 70) > 90,
    effects: { crime: 5, freedomIndex: -5 },
    voterEffects: { religious: -20, liberals: -10 },
    cascades: ['terrorism_threat'],
  },
  {
    id: 'immigration_crisis',
    name: 'Immigration Crisis',
    description: 'Overwhelmed border services and strained public resources.',
    icon: '🚢',
    category: 'social',
    severity: 'severe',
    triggerCondition: (p) => (p.immigration ?? 50) > 75 && (p.border_security ?? 45) < 25,
    effects: { crime: 5, nationalSecurity: -10 },
    voterEffects: { patriots: -25, rural: -15, religious: -10, liberals: 5 },
    cascades: ['far_right_rise'],
  },
  {
    id: 'cultural_divide',
    name: 'Cultural Divide',
    description: 'Society is increasingly polarized along cultural and political lines.',
    icon: '🔀',
    category: 'social',
    severity: 'moderate',
    triggerCondition: (_p, sim) => sim.equality < 30 && sim.freedomIndex > 70,
    effects: { crime: 5 },
    voterEffects: { patriots: -10, liberals: -10 },
  },
  {
    id: 'education_crisis',
    name: 'Education Crisis',
    description: 'Underfunded schools are producing poorly educated graduates.',
    icon: '📚',
    category: 'social',
    severity: 'moderate',
    triggerCondition: (p) => (p.education ?? 50) < 25,
    effects: { educationIndex: -20, gdpGrowth: -1 },
    voterEffects: { youth: -20, workers: -5 },
    cascades: ['brain_drain'],
  },
  {
    id: 'healthcare_collapse',
    name: 'Healthcare System Collapse',
    description: 'Hospitals are overwhelmed and unable to provide basic care.',
    icon: '🏥',
    category: 'social',
    severity: 'critical',
    triggerCondition: (p) => (p.healthcare ?? 50) < 20,
    effects: { healthIndex: -30 },
    voterEffects: { retirees: -25, workers: -15, rural: -10, urban: -10 },
  },
  // ===== SECURITY =====
  {
    id: 'terrorism_threat',
    name: 'Terrorism Threat',
    description: 'Intelligence reports indicate credible terrorist threats.',
    icon: '🎯',
    category: 'security',
    severity: 'critical',
    triggerCondition: (p) => (p.border_security ?? 45) < 25 && (p.intelligence ?? 30) < 20,
    effects: { nationalSecurity: -20, crime: 5 },
    voterEffects: { patriots: -20, retirees: -10, business: -10 },
  },
  {
    id: 'organized_crime',
    name: 'Organized Crime Wave',
    description: 'Criminal networks are expanding their influence throughout the country.',
    icon: '🔫',
    category: 'security',
    severity: 'severe',
    triggerCondition: (p, sim) => (p.police ?? 50) < 30 && sim.corruption > 60,
    effects: { crime: 20, gdpGrowth: -1, nationalSecurity: -5 },
    voterEffects: { retirees: -15, business: -15, urban: -10 },
  },
  {
    id: 'military_coup_risk',
    name: 'Military Coup Risk',
    description: 'Generals are whispering about taking matters into their own hands.',
    icon: '⚔️',
    category: 'security',
    severity: 'critical',
    triggerCondition: (p, sim) => (p.military ?? 40) > 80 && sim.freedomIndex < 25,
    effects: { freedomIndex: -10 },
    voterEffects: { liberals: -25, youth: -15 },
  },
  {
    id: 'cyberattacks',
    name: 'Cyberattack Campaign',
    description: 'Critical infrastructure is under sustained cyber assault.',
    icon: '🖥️',
    category: 'security',
    severity: 'moderate',
    triggerCondition: (p) => (p.tech_research ?? 35) < 20 && (p.intelligence ?? 30) < 25,
    effects: { gdpGrowth: -1, nationalSecurity: -10 },
    voterEffects: { business: -10, urban: -5 },
  },
  {
    id: 'police_brutality',
    name: 'Police Brutality Scandal',
    description: 'Widespread reports of excessive force by law enforcement.',
    icon: '🚨',
    category: 'security',
    severity: 'moderate',
    triggerCondition: (p, sim) => (p.police ?? 50) > 80 && sim.freedomIndex < 40,
    effects: { freedomIndex: -10, crime: -5 },
    voterEffects: { liberals: -20, youth: -15, workers: -5 },
  },
  {
    id: 'border_conflict',
    name: 'Border Conflict',
    description: 'Tensions with a neighboring state threaten to escalate.',
    icon: '🗺️',
    category: 'security',
    severity: 'severe',
    triggerCondition: (p) => (p.military ?? 40) < 20 && (p.border_security ?? 45) < 20,
    effects: { nationalSecurity: -15, gdpGrowth: -1 },
    voterEffects: { patriots: -20 },
  },
  // ===== ENVIRONMENT =====
  {
    id: 'climate_disaster',
    name: 'Climate Disaster',
    description: 'Extreme weather events are devastating communities.',
    icon: '🌪️',
    category: 'environment',
    severity: 'critical',
    triggerCondition: (p, _sim, turns) => (p.env_regulations ?? 40) < 25 && turns >= 6,
    effects: { gdpGrowth: -2, healthIndex: -10, pollution: 15 },
    voterEffects: { environmentalists: -25, rural: -15, urban: -10 },
  },
  {
    id: 'water_crisis',
    name: 'Water Crisis',
    description: 'Contaminated water supplies threaten public health.',
    icon: '💧',
    category: 'environment',
    severity: 'severe',
    triggerCondition: (_p, sim) => sim.pollution > 75,
    effects: { healthIndex: -15, gdpGrowth: -1 },
    voterEffects: { environmentalists: -20, rural: -15, urban: -10 },
  },
  {
    id: 'energy_crisis',
    name: 'Energy Crisis',
    description: 'Power shortages and soaring energy bills.',
    icon: '⚡',
    category: 'environment',
    severity: 'severe',
    triggerCondition: (p) => (p.renewables ?? 30) < 15 && (p.carbon_tax ?? 20) < 10,
    effects: { gdpGrowth: -2, inflation: 3 },
    voterEffects: { business: -15, workers: -10, urban: -10 },
  },
  {
    id: 'deforestation',
    name: 'Deforestation Crisis',
    description: 'Rapid forest loss is destroying ecosystems.',
    icon: '🌲',
    category: 'environment',
    severity: 'moderate',
    triggerCondition: (p) => (p.env_regulations ?? 40) < 20 && (p.agriculture ?? 35) > 70,
    effects: { pollution: 15, healthIndex: -5 },
    voterEffects: { environmentalists: -20, rural: -5 },
  },
  {
    id: 'air_pollution',
    name: 'Severe Air Pollution',
    description: 'Smog blankets major cities, causing respiratory diseases.',
    icon: '🏭',
    category: 'environment',
    severity: 'moderate',
    triggerCondition: (_p, sim) => sim.pollution > 65,
    effects: { healthIndex: -10 },
    voterEffects: { environmentalists: -15, urban: -15, retirees: -5 },
  },
  // ===== MORE ECONOMIC =====
  {
    id: 'stock_market_crash',
    name: 'Stock Market Crash',
    description: 'Markets plummeting. Investor confidence shattered.',
    icon: '📉',
    category: 'economic',
    severity: 'severe',
    triggerCondition: (_p, sim) => sim.gdpGrowth < -3 && sim.inflation > 8,
    effects: { gdpGrowth: -2, unemployment: 4, equality: -10 },
    voterEffects: { business: -20, retirees: -15 },
    cascades: ['debt_crisis'],
  },
  {
    id: 'wage_stagnation',
    name: 'Wage Stagnation',
    description: 'Workers\' wages haven\'t kept up with the cost of living.',
    icon: '💰',
    category: 'economic',
    severity: 'moderate',
    triggerCondition: (p, sim) => (p.minimum_wage ?? 40) < 30 && sim.inflation > 5,
    effects: { equality: -10 },
    voterEffects: { workers: -15, youth: -10 },
  },
  {
    id: 'startup_boom',
    name: 'Startup Boom',
    description: 'New businesses are flourishing, creating innovation and jobs.',
    icon: '🌟',
    category: 'economic',
    severity: 'mild',
    triggerCondition: (p) => (p.corporate_tax ?? 30) < 25 && (p.tech_research ?? 35) > 55,
    effects: { gdpGrowth: 1.5, unemployment: -2 },
    voterEffects: { youth: 10, business: 15 },
  },
  // ===== MORE SOCIAL =====
  {
    id: 'media_censorship',
    name: 'Media Censorship Outcry',
    description: 'Restrictions on press freedom spark protests.',
    icon: '📵',
    category: 'social',
    severity: 'moderate',
    triggerCondition: (p) => (p.press_freedom ?? 65) < 25,
    effects: { freedomIndex: -15 },
    voterEffects: { liberals: -25, youth: -15 },
  },
  {
    id: 'labor_strikes',
    name: 'Labor Strikes',
    description: 'Workers across multiple sectors walk off the job.',
    icon: '✊',
    category: 'social',
    severity: 'moderate',
    triggerCondition: (p) => (p.minimum_wage ?? 40) < 20 && (p.unemployment_benefits ?? 40) < 20,
    effects: { gdpGrowth: -1.5, unemployment: 2 },
    voterEffects: { workers: -20, business: -10 },
  },
  {
    id: 'pension_crisis',
    name: 'Pension Crisis',
    description: 'The pension fund is running dry. Retirees face poverty.',
    icon: '👴',
    category: 'social',
    severity: 'severe',
    triggerCondition: (p) => (p.pensions ?? 45) < 20,
    effects: { equality: -10, healthIndex: -5 },
    voterEffects: { retirees: -30 },
  },
  {
    id: 'youth_unemployment',
    name: 'Youth Unemployment Crisis',
    description: 'A generation with no job prospects. Social unrest looms.',
    icon: '👤',
    category: 'social',
    severity: 'severe',
    triggerCondition: (_p, sim) => sim.unemployment > 15 && sim.educationIndex < 40,
    effects: { crime: 10 },
    voterEffects: { youth: -25, liberals: -5 },
    cascades: ['brain_drain'],
  },
  // ===== MORE SECURITY =====
  {
    id: 'prison_overcrowding',
    name: 'Prison Overcrowding',
    description: 'Prisons at 200% capacity. Conditions are inhumane.',
    icon: '🔒',
    category: 'security',
    severity: 'moderate',
    triggerCondition: (_p, sim) => sim.crime > 70,
    effects: { freedomIndex: -5, healthIndex: -3 },
    voterEffects: { liberals: -10 },
  },
  {
    id: 'spy_scandal',
    name: 'Espionage Scandal',
    description: 'Foreign agents discovered in key government positions.',
    icon: '🕵️',
    category: 'security',
    severity: 'severe',
    triggerCondition: (p) => (p.intelligence ?? 30) < 15,
    effects: { nationalSecurity: -15, corruption: 10 },
    voterEffects: { patriots: -15, business: -5 },
  },
];

export function checkSituations(
  policies: Record<string, number>,
  sim: SimulationState,
  activeSituationIds: string[],
  turnsSinceStart: number,
  budget?: BudgetState
): string[] {
  const triggered: string[] = [];
  
  for (const situation of SITUATIONS) {
    // Skip already active
    if (activeSituationIds.includes(situation.id)) continue;
    
    try {
      if (situation.triggerCondition(policies, sim, turnsSinceStart, budget)) {
        triggered.push(situation.id);
      }
    } catch {
      // Ignore evaluation errors
    }
  }
  
  return triggered;
}

export function getSituationById(id: string): SituationDefinition | undefined {
  return SITUATIONS.find(s => s.id === id);
}

// Check if a situation should resolve (conditions no longer met)
export function shouldResolveSituation(
  id: string,
  policies: Record<string, number>,
  sim: SimulationState,
  turnsSinceStart: number,
  budget?: BudgetState
): boolean {
  const situation = getSituationById(id);
  if (!situation) return true;
  
  try {
    return !situation.triggerCondition(policies, sim, turnsSinceStart, budget);
  } catch {
    return false;
  }
}
