import { VoterGroupDefinition } from './types';

export const VOTER_GROUPS: VoterGroupDefinition[] = [
  {
    id: 'workers',
    name: 'Workers',
    populationShare: 0.18,
    concerns: {
      unemployment: -0.8,
      equality: 0.6,
      gdpGrowth: 0.3,
      inflation: -0.4,
    },
    policyPreferences: {
      minimum_wage: 70,
      unemployment_benefits: 65,
      healthcare: 70,
      education: 60,
      income_tax: 40,
      pensions: 60,
    },
  },
  {
    id: 'business',
    name: 'Business',
    populationShare: 0.12,
    concerns: {
      gdpGrowth: 0.8,
      unemployment: -0.3,
      inflation: -0.5,
      corruption: -0.4,
    },
    policyPreferences: {
      corporate_tax: 20,
      income_tax: 25,
      trade_openness: 80,
      govt_spending: 30,
      env_regulations: 30,
      tech_research: 70,
    },
  },
  {
    id: 'youth',
    name: 'Youth',
    populationShare: 0.14,
    concerns: {
      freedomIndex: 0.7,
      educationIndex: 0.6,
      unemployment: -0.5,
      pollution: -0.3,
    },
    policyPreferences: {
      education: 80,
      civil_rights: 80,
      drug_policy: 65,
      press_freedom: 75,
      tech_research: 70,
      renewables: 60,
    },
  },
  {
    id: 'retirees',
    name: 'Retirees',
    populationShare: 0.15,
    concerns: {
      healthIndex: 0.8,
      crime: -0.5,
      inflation: -0.6,
      nationalSecurity: 0.3,
    },
    policyPreferences: {
      pensions: 85,
      healthcare: 80,
      police: 65,
      military: 55,
      immigration: 35,
    },
  },
  {
    id: 'urban',
    name: 'Urban Professionals',
    populationShare: 0.11,
    concerns: {
      gdpGrowth: 0.5,
      pollution: -0.4,
      freedomIndex: 0.5,
      educationIndex: 0.4,
    },
    policyPreferences: {
      public_transport: 75,
      urban_dev: 70,
      tech_research: 65,
      education: 65,
      housing_subsidies: 60,
      env_regulations: 55,
    },
  },
  {
    id: 'rural',
    name: 'Rural Communities',
    populationShare: 0.10,
    concerns: {
      unemployment: -0.5,
      crime: -0.4,
      gdpGrowth: 0.3,
    },
    policyPreferences: {
      agriculture: 85,
      roads_rail: 70,
      border_security: 60,
      gun_control: 25,
      immigration: 30,
      religious_freedom: 70,
    },
  },
  {
    id: 'environmentalists',
    name: 'Environmentalists',
    populationShare: 0.06,
    concerns: {
      pollution: -0.9,
      healthIndex: 0.3,
    },
    policyPreferences: {
      env_regulations: 90,
      renewables: 90,
      carbon_tax: 80,
      public_transport: 70,
      agriculture: 40,
    },
  },
  {
    id: 'religious',
    name: 'Religious Groups',
    populationShare: 0.05,
    concerns: {
      freedomIndex: -0.2,
      crime: -0.5,
      equality: 0.2,
    },
    policyPreferences: {
      religious_freedom: 90,
      drug_policy: 15,
      immigration: 40,
      civil_rights: 40,
      pensions: 60,
    },
  },
  {
    id: 'liberals',
    name: 'Liberals',
    populationShare: 0.05,
    concerns: {
      freedomIndex: 0.9,
      equality: 0.6,
      corruption: -0.3,
    },
    policyPreferences: {
      civil_rights: 90,
      press_freedom: 85,
      immigration: 75,
      drug_policy: 70,
      police: 35,
      military: 30,
    },
  },
  {
    id: 'patriots',
    name: 'Patriots',
    populationShare: 0.04,
    concerns: {
      nationalSecurity: 0.9,
      crime: -0.5,
    },
    policyPreferences: {
      military: 85,
      border_security: 80,
      intelligence: 75,
      immigration: 15,
      foreign_aid: 15,
    },
  },
];
